#公共配置与profiles选择无关
server:
  port: 9101
spring:
  datasource:
    url: jdbc:mysql://172.18.0.58:3306/tzzd?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  redis:
    host: 172.18.0.58
    database: 0
    port: 6379
    password: ''
  dubbo:
    registry:
      address: zookeeper://zookeeper:2181
    protocol:
      name: dubbo
      port: 20881
logging:
  level:
    com.ttit.attachment.provider.dao: debug
business:
  file-upload-path: /opt/tzzd/data
  file-download-path: http://172.18.0.58:9102/attachment/download/