#公共配置与profiles选择无关
server:
  port: 9104
spring:
  dubbo:
    registry:
      address: zookeeper://zookeeper:2181
    protocol:
      name: dubbo
      port: 20881
business:
  file-upload-path: /opt/tzzd/data