#公共配置与profiles选择无关
server:
  port: 9102
spring:
  application:
    name: syslog-web
  profiles:
    active: dev
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 102400KB
      # 一次请求文件大小
      max-request-size: 102400KB
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  dubbo:
    application:
      name: syslog-web
      id: syslog-web
    registry:
      address: zookeeper://172.18.0.58:2181
    protocol:
      name: dubbo
      port: 20880
    consumer:
      timeout: 5000
