#公共配置与profiles选择无关
spring:
  application:
    name: attachment-provider
  profiles:
    active: dev
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 102400KB
      # 一次请求文件大小
      max-request-size: 102400KB
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.0.58:3306/tzzd?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  redis:
    host: 172.18.0.58
    database: 0
    port: 6379
    password: ''
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
  dubbo:
    application:
      name: attachment-provider
      id: attachment-provider
    registry:
      address: zookeeper://172.18.0.58:2181
    server: true
    protocol:
      name: dubbo
      port: 20881
    scan: com.ttit.attachment.provider.service
mybatis:
  type-aliases-package: com.ttit.tzzd.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  level:
    com.ttit.attachment.provider.dao: debug
business:
  server:
    #对外暴露附件服务的根路径
    atta-url: localhost:9100
  file-upload-path: E:\Projects\tzzd\softs\