#公共配置与profiles选择无关
server:
  port: 9103
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/tzzd?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123
  redis:
    host: redis
    database: 0
    port: 6379
    password: ''
  dubbo:
    registry:
      address: zookeeper://zookeeper:2181
    protocol:
      name: dubbo
      port: 20881
logging:
  level:
    com.ttit.attachment.provider.dao: debug
business:
  dict:
    #使用内建版数据字典
    save-type: "app"
  time-limit:
    #设备连接时限，单位秒
    #上次收到信号，在online时间内，视为在线
    online: 10
    #上次收到信号，超过online时间，小于breaked时间，视为中断；大于breaked时间，视为离线
    breaked: 40
  file-upload-path: /opt/tzzd/data
  file-download-path: http://172.18.0.58:9102/attachment/download/